!#PYFT transfo: --addArgInTree XX REAL::XX 0 --restrictScope module:ADDARGINTREE/sub:FOO1/sub:FOO3 --stopScopes module:ADDARGINTREE/sub:FOO1/sub:FOO2

MODULE ADDARGINTREE
  CONTAINS
  SUBROUTINE FOO1()
    CALL FOO2()
  CONTAINS
    SUBROUTINE FOO2()
      CALL FOO3()
      CALL FOO4()
    END SUBROUTINE FOO2
    SUBROUTINE FOO3()
    END SUBROUTINE FOO3
    SUBROUTINE FOO4()
    END SUBROUTINE FOO4
  END SUBROUTINE FOO1
END MODULE ADDARGINTREE
