!#PYFT transfo: --replaceAutomaticWithAllocatable

SUBROUTINE ALLOC()
IMPLICIT NONE

!Pas des tableaux
REAL :: Z
INTEGER, PARAMETER :: ISIZE=5

!Z1 est un tableau


REAL, DIMENSION(:), ALLOCATABLE :: Z1
!Z2 est également un tableau


REAL, DIMENSION(:), ALLOCATABLE :: Z2
!Z3 est un tableau Z4 ne l'est pas
REAL, DIMENSION(:), ALLOCATABLE :: Z3
REAL :: Z4

!Multipligne 1
REAL(KIND=8), DIMENSION(:), ALLOCATABLE :: Z7
REAL(KIND=8), DIMENSION(:), ALLOCATABLE :: Z6


REAL(KIND=8), DIMENSION(:), ALLOCATABLE :: Z5
!Multipligne 2
REAL, DIMENSION(:), ALLOCATABLE :: Z10
REAL, DIMENSION(:,:), ALLOCATABLE :: Z9
REAL :: Z8  ! Z25, Z26
         
ALLOCATE(Z1(ISIZE))
ALLOCATE(Z2(5))
ALLOCATE(Z3(5))
ALLOCATE(Z5(5))
ALLOCATE(Z6(5))
ALLOCATE(Z7(5))
ALLOCATE(Z9(5, 3))
ALLOCATE(Z10(5))
DEALLOCATE(Z10)
DEALLOCATE(Z9)
DEALLOCATE(Z7)
DEALLOCATE(Z6)
DEALLOCATE(Z5)
DEALLOCATE(Z3)
DEALLOCATE(Z2)
DEALLOCATE(Z1)
END SUBROUTINE ALLOC
