!#PYFT transfo: --empty --simplify

MODULE EMPTYMOD
  REAL :: XMOD
  CONTAINS
    SUBROUTINE EMPTYSUB(P)
      REAL, INTENT(IN) :: P
      REAL :: Z
      PRINT*, Z, P
      CONTAINS
        SUBROUTINE INC(K)
          INTEGER, INTENT(IN) :: K
          INTEGER :: J
          PRINT*, J, K
        END SUBROUTINE INC
    END SUBROUTINE EMPTYSUB
END MODULE EMPTYMOD

SUBROUTINE EMPTYSUB(P)
  REAL, INTENT(IN) :: P
  REAL :: Z
  PRINT*, Z, P
  CONTAINS
    SUBROUTINE INC(K)
      INTEGER, INTENT(IN) :: K
      INTEGER :: J
      PRINT*, J, K
    END SUBROUTINE INC
END SUBROUTINE EMPTYSUB

