MODULE EMPTYMOD
  REAL :: XMOD
  CONTAINS
    SUBROUTINE EMPTYSUB(P)
      REAL, INTENT(IN) :: P
      END SUBROUTINE EMPTYSUB
END MODULE EMPTYMOD
SUBROUTINE EMPTYSUB(P)
  REAL, INTENT(IN) :: P
  END SUBROUTINE EMPTYSUB
