!#PYFT transfo: --mathFunctoBRFunc

SUBROUTINE FOO
USE MODI_BITREP
  PRINT*, BR_P2(I), BR_P3(I), BR_P4(I), BR_POW(I,K)
  PRINT*, BR_LOG(I), BR_EXP(I), BR_COS(I), BR_SIN(I), BR_ASIN(I), BR_ATAN(I), BR_ATAN2(I, J)
END SUBROUTINE FOO
