MODULE MODE_ICE4_FAST_RH1
IMPLICIT NONE
CONTAINS
SUBROUTINE ICE4_FAST_RH(CST, PARAMI, ICEP, ICED, KPROMA, KSIZE, LDSOFT, LDCOMPUTE, LDWETG,  PRHODREF, PLVFACT, PLSFACT, PPRES,  PDV, PKA, PCJ,  PLBDAS, PLBDAG, PLBDAR, PLBDAH,  PT, PRVT, PRCT, PRRT, PRIT, PRST, PRGT, PRHT,  PRCWETH, PRIWETH, PRSWETH, PRGWETH, PRRWETH,  PRCDRYH, PRIDRYH, PRSDRYH, PRRDRYH, PRGDRYH, PRDRYHG, PRHMLTR,  PRH_TEND)
USE MODD_CST, ONLY: CST_T
USE MODD_PARAM_ICE_N, ONLY: PARAM_ICE_T
USE MODD_RAIN_ICE_DESCR_N, ONLY: RAIN_ICE_DESCR_T
USE MODD_RAIN_ICE_PARAM_N, ONLY: RAIN_ICE_PARAM_T
USE YOMHOOK, ONLY: LHOOK, DR_HOOK, JPHOOK
IMPLICIT NONE
TYPE(CST_T), INTENT(IN) :: CST
TYPE(PARAM_ICE_T), INTENT(IN) :: PARAMI
TYPE(RAIN_ICE_PARAM_T), INTENT(IN) :: ICEP
TYPE(RAIN_ICE_DESCR_T), INTENT(IN) :: ICED
INTEGER, INTENT(IN) :: KPROMA, KSIZE
LOGICAL, INTENT(IN) :: LDSOFT
LOGICAL, DIMENSION(KPROMA), INTENT(IN) :: LDCOMPUTE
LOGICAL, DIMENSION(KPROMA), INTENT(IN) :: LDWETG
REAL, DIMENSION(KPROMA), INTENT(IN) :: PRHODREF
REAL, DIMENSION(KPROMA), INTENT(IN) :: PLVFACT
REAL, DIMENSION(KPROMA), INTENT(IN) :: PLSFACT
REAL, DIMENSION(KPROMA), INTENT(IN) :: PPRES
REAL, DIMENSION(KPROMA), INTENT(IN) :: PDV
REAL, DIMENSION(KPROMA), INTENT(IN) :: PKA
REAL, DIMENSION(KPROMA), INTENT(IN) :: PCJ
REAL, DIMENSION(KPROMA), INTENT(IN) :: PLBDAS
REAL, DIMENSION(KPROMA), INTENT(IN) :: PLBDAG
REAL, DIMENSION(KPROMA), INTENT(IN) :: PLBDAR
REAL, DIMENSION(KPROMA), INTENT(IN) :: PLBDAH
REAL, DIMENSION(KPROMA), INTENT(IN) :: PT
REAL, DIMENSION(KPROMA), INTENT(IN) :: PRVT
REAL, DIMENSION(KPROMA), INTENT(IN) :: PRCT
REAL, DIMENSION(KPROMA), INTENT(IN) :: PRRT
REAL, DIMENSION(KPROMA), INTENT(IN) :: PRIT
REAL, DIMENSION(KPROMA), INTENT(IN) :: PRST
REAL, DIMENSION(KPROMA), INTENT(IN) :: PRGT
REAL, DIMENSION(KPROMA), INTENT(IN) :: PRHT
REAL, DIMENSION(KPROMA), INTENT(OUT) :: PRCWETH
REAL, DIMENSION(KPROMA), INTENT(OUT) :: PRIWETH
REAL, DIMENSION(KPROMA), INTENT(OUT) :: PRSWETH
REAL, DIMENSION(KPROMA), INTENT(OUT) :: PRGWETH
REAL, DIMENSION(KPROMA), INTENT(OUT) :: PRRWETH
REAL, DIMENSION(KPROMA), INTENT(OUT) :: PRCDRYH
REAL, DIMENSION(KPROMA), INTENT(OUT) :: PRIDRYH
REAL, DIMENSION(KPROMA), INTENT(OUT) :: PRSDRYH
REAL, DIMENSION(KPROMA), INTENT(OUT) :: PRRDRYH
REAL, DIMENSION(KPROMA), INTENT(OUT) :: PRGDRYH
REAL, DIMENSION(KPROMA), INTENT(OUT) :: PRDRYHG
REAL, DIMENSION(KPROMA), INTENT(INOUT) :: PRHMLTR
REAL, DIMENSION(KPROMA, 10), INTENT(INOUT) :: PRH_TEND
INTEGER, PARAMETER :: IRCWETH=1, IRRWETH=2, IRIDRYH=3, IRIWETH=4, IRSDRYH=5, IRSWETH=6, IRGDRYH=7, IRGWETH=8,  IFREEZ1=9, IFREEZ2=10
LOGICAL, DIMENSION(KPROMA) :: GWET
INTEGER :: IGWET
REAL, DIMENSION(KPROMA) :: ZBUF1, ZBUF2, ZBUF3
INTEGER, DIMENSION(KPROMA) :: IBUF1, IBUF2, IBUF3
REAL, DIMENSION(KPROMA) :: ZZW,  ZRDRYH_INIT, ZRWETH_INIT,  ZRDRYHG
INTEGER :: JL
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE
LOGICAL, DIMENSION(KPROMA) :: LLWETH, LLDRYH
IF (LHOOK) CALL DR_HOOK('ICE4_FAST_RH', 0, ZHOOK_HANDLE)
DO JL=1, KSIZE
IF (PRHT(JL) > ICED%XRTMIN(7) .AND. PRCT(JL) > ICED%XRTMIN(2) .AND. LDCOMPUTE(JL)) THEN
IF (.NOT. LDSOFT) THEN
PRH_TEND(JL, IRCWETH) = PLBDAH(JL) ** (ICED%XCXH - ICED%XDH - 2.0) * PRHODREF(JL) ** (- ICED%XCEXVT)
PRH_TEND(JL, IRCWETH) = ICEP%XFWETH * PRCT(JL) * PRH_TEND(JL, IRCWETH)
END IF
ELSE
PRH_TEND(JL, IRCWETH) = 0.
END IF
IF (PRHT(JL) > ICED%XRTMIN(7) .AND. PRIT(JL) > ICED%XRTMIN(4) .AND. LDCOMPUTE(JL)) THEN
IF (.NOT. LDSOFT) THEN
PRH_TEND(JL, IRIWETH) = PLBDAH(JL) ** (ICED%XCXH - ICED%XDH - 2.0) * PRHODREF(JL) ** (- ICED%XCEXVT)
PRH_TEND(JL, IRIWETH) = ICEP%XFWETH * PRIT(JL) * PRH_TEND(JL, IRIWETH)
PRH_TEND(JL, IRIDRYH) = PRH_TEND(JL, IRIWETH) * (ICEP%XCOLIH * EXP(ICEP%XCOLEXIH * (PT(JL) - CST%XTT)))
END IF
ELSE
PRH_TEND(JL, IRIWETH) = 0.
PRH_TEND(JL, IRIDRYH) = 0.
END IF
END DO
DO JL=1, KSIZE
IF (PRHT(JL) > ICED%XRTMIN(7) .AND. PRST(JL) > ICED%XRTMIN(5) .AND. LDCOMPUTE(JL)) THEN
GWET(JL) = .TRUE.
ELSE
GWET(JL) = .FALSE.
PRH_TEND(JL, IRSWETH) = 0.
PRH_TEND(JL, IRSDRYH) = 0.
END IF
END DO
IF (.NOT. LDSOFT) THEN
CALL INTERP_MICRO_2D(KPROMA, KSIZE, PLBDAH(:), PLBDAS(:), ICEP%NWETLBDAH, ICEP%NWETLBDAS,  ICEP%XWETINTP1H, ICEP%XWETINTP2H, ICEP%XWETINTP1S, ICEP%XWETINTP2S,  PARAMI%LPACK_INTERP, GWET(:), IBUF1(:), IBUF2(:), IBUF3(:), ZBUF1(:), ZBUF2(:), ZBUF3(:),  IGWET,  ICEP%XKER_SWETH(:, :), ZZW(:))
IF (IGWET > 0) THEN
!$mnh_expand_where(JL=1:KSIZE)
WHERE (GWET(1:KSIZE))
#ifdef REPRO48
PRH_TEND(1:KSIZE, IRSWETH) = ICEP%XFSWETH * ZZW(1:KSIZE)  * (PLBDAS(1:KSIZE) ** (ICED%XCXS - ICED%XBS)) * (PLBDAH(1:KSIZE) ** ICED%XCXH)  * (PRHODREF(1:KSIZE) ** (- ICED%XCEXVT - 1.))  * (ICEP%XLBSWETH1 / (PLBDAH(1:KSIZE) ** 2) +  ICEP%XLBSWETH2 / (PLBDAH(1:KSIZE) * PLBDAS(1:KSIZE)) +  ICEP%XLBSWETH3 / (PLBDAS(1:KSIZE) ** 2))
#else
PRH_TEND(1:KSIZE, IRSWETH) = ICEP%XFSWETH * ZZW(1:KSIZE)  * (PRST(1:KSIZE)) * (PLBDAH(1:KSIZE) ** ICED%XCXH)  * (PRHODREF(1:KSIZE) ** (- ICED%XCEXVT))  * (ICEP%XLBSWETH1 / (PLBDAH(1:KSIZE) ** 2) +  ICEP%XLBSWETH2 / (PLBDAH(1:KSIZE) * PLBDAS(1:KSIZE)) +  ICEP%XLBSWETH3 / (PLBDAS(1:KSIZE) ** 2))
#endif
PRH_TEND(1:KSIZE, IRSDRYH) = PRH_TEND(1:KSIZE, IRSWETH) * (ICEP%XCOLSH * EXP(ICEP%XCOLEXSH * (PT(1:KSIZE) - CST%XTT)))
END WHERE
!$mnh_end_expand_where(JL=1:KSIZE)
END IF
END IF
DO JL=1, KSIZE
IF (PRHT(JL) > ICED%XRTMIN(7) .AND. PRGT(JL) > ICED%XRTMIN(6) .AND. LDCOMPUTE(JL)) THEN
GWET(JL) = .TRUE.
ELSE
GWET(JL) = .FALSE.
PRH_TEND(JL, IRGWETH) = 0.
PRH_TEND(JL, IRGDRYH) = 0.
END IF
END DO
IF (.NOT. LDSOFT) THEN
CALL INTERP_MICRO_2D(KPROMA, KSIZE, PLBDAH(:), PLBDAG(:), ICEP%NWETLBDAH, ICEP%NWETLBDAG,  ICEP%XWETINTP1H, ICEP%XWETINTP2H, ICEP%XWETINTP1G, ICEP%XWETINTP2G,  PARAMI%LPACK_INTERP, GWET(:), IBUF1(:), IBUF2(:), IBUF3(:), ZBUF1(:), ZBUF2(:), ZBUF3(:),  IGWET,  ICEP%XKER_GWETH(:, :), ZZW(:))
IF (IGWET > 0) THEN
!$mnh_expand_where(JL=1:KSIZE)
WHERE (GWET(1:KSIZE))
PRH_TEND(1:KSIZE, IRGWETH) = ICEP%XFGWETH * ZZW(1:KSIZE)  * (PLBDAG(1:KSIZE) ** (ICED%XCXG - ICED%XBG)) * (PLBDAH(1:KSIZE) ** ICED%XCXH)  * (PRHODREF(1:KSIZE) ** (- ICED%XCEXVT - 1.))  * (ICEP%XLBGWETH1 / (PLBDAH(1:KSIZE) ** 2) +  ICEP%XLBGWETH2 / (PLBDAH(1:KSIZE) * PLBDAG(1:KSIZE)) +  ICEP%XLBGWETH3 / (PLBDAG(1:KSIZE) ** 2))
PRH_TEND(1:KSIZE, IRGDRYH) = PRH_TEND(1:KSIZE, IRGWETH)
END WHERE
WHERE (GWET(1:KSIZE) .AND. .NOT. LDWETG(1:KSIZE))
PRH_TEND(1:KSIZE, IRGDRYH) = PRH_TEND(1:KSIZE, IRGDRYH) * (ICEP%XCOLGH * EXP(ICEP%XCOLEXGH * (PT(1:KSIZE) - CST%XTT)))
END WHERE
!$mnh_end_expand_where(JL=1:KSIZE)
END IF
END IF
DO JL=1, KSIZE
IF (PRHT(JL) > ICED%XRTMIN(7) .AND. PRRT(JL) > ICED%XRTMIN(3) .AND. LDCOMPUTE(JL)) THEN
GWET(JL) = .TRUE.
ELSE
GWET(JL) = .FALSE.
PRH_TEND(JL, IRRWETH) = 0.
END IF
END DO
IF (.NOT. LDSOFT) THEN
CALL INTERP_MICRO_2D(KPROMA, KSIZE, PLBDAH(:), PLBDAR(:), ICEP%NWETLBDAH, ICEP%NWETLBDAR,  ICEP%XWETINTP1H, ICEP%XWETINTP2H, ICEP%XWETINTP1R, ICEP%XWETINTP2R,  PARAMI%LPACK_INTERP, GWET(:), IBUF1(:), IBUF2(:), IBUF3(:), ZBUF1(:), ZBUF2(:), ZBUF3(:),  IGWET,  ICEP%XKER_RWETH(:, :), ZZW(:))
IF (IGWET > 0) THEN
!$mnh_expand_where(JL=1:KSIZE)
WHERE (GWET(1:KSIZE))
PRH_TEND(1:KSIZE, IRRWETH) = ICEP%XFRWETH * ZZW(1:KSIZE)  * (PLBDAR(1:KSIZE) ** (- 4)) * (PLBDAH(1:KSIZE) ** ICED%XCXH)  * (PRHODREF(1:KSIZE) ** (- ICED%XCEXVT - 1.))  * (ICEP%XLBRWETH1 / (PLBDAH(1:KSIZE) ** 2) +  ICEP%XLBRWETH2 / (PLBDAH(1:KSIZE) * PLBDAR(1:KSIZE)) +  ICEP%XLBRWETH3 / (PLBDAR(1:KSIZE) ** 2))
END WHERE
!$mnh_end_expand_where(JL=1:KSIZE)
END IF
END IF
DO JL=1, KSIZE
ZRDRYH_INIT(JL) = PRH_TEND(JL, IRCWETH) + PRH_TEND(JL, IRIDRYH) +  PRH_TEND(JL, IRSDRYH) + PRH_TEND(JL, IRRWETH) + PRH_TEND(JL, IRGDRYH)
END DO
DO JL=1, KSIZE
IF (PRHT(JL) > ICED%XRTMIN(7) .AND. LDCOMPUTE(JL)) THEN
IF (.NOT. LDSOFT) THEN
PRH_TEND(JL, IFREEZ1) = PRVT(JL) * PPRES(JL) / (CST%XEPSILO + PRVT(JL))
IF (PARAMI%LEVLIMIT) THEN
PRH_TEND(JL, IFREEZ1) = MIN(PRH_TEND(JL, IFREEZ1), EXP(CST%XALPI - CST%XBETAI / PT(JL) - CST%XGAMI * ALOG(PT(JL))))
END IF
PRH_TEND(JL, IFREEZ1) = PKA(JL) * (CST%XTT - PT(JL)) +  (PDV(JL) * (CST%XLVTT + (CST%XCPV - CST%XCL) * (PT(JL) - CST%XTT))  * (CST%XESTT - PRH_TEND(JL, IFREEZ1)) / (CST%XRV * PT(JL)))
PRH_TEND(JL, IFREEZ1) = PRH_TEND(JL, IFREEZ1) * (ICEP%X0DEPH * PLBDAH(JL) ** ICEP%XEX0DEPH +  ICEP%X1DEPH * PCJ(JL) * PLBDAH(JL) ** ICEP%XEX1DEPH) /  (PRHODREF(JL) * (CST%XLMTT - CST%XCL * (CST%XTT - PT(JL))))
PRH_TEND(JL, IFREEZ2) = (PRHODREF(JL) * (CST%XLMTT + (CST%XCI - CST%XCL) * (CST%XTT - PT(JL)))) /  (PRHODREF(JL) * (CST%XLMTT - CST%XCL * (CST%XTT - PT(JL))))
END IF
ZRWETH_INIT(JL) = MAX(PRH_TEND(JL, IRIWETH) + PRH_TEND(JL, IRSWETH) + PRH_TEND(JL, IRGWETH),  MAX(0., PRH_TEND(JL, IFREEZ1) +  PRH_TEND(JL, IFREEZ2) * (PRH_TEND(JL, IRIWETH) + PRH_TEND(JL, IRSWETH) + PRH_TEND(JL, IRGWETH))))
LLWETH(JL) = MAX(0., ZRWETH_INIT(JL) - PRH_TEND(JL, IRIWETH) - PRH_TEND(JL, IRSWETH) - PRH_TEND(JL, IRGWETH)) <=  MAX(0., ZRDRYH_INIT(JL) - PRH_TEND(JL, IRIDRYH) - PRH_TEND(JL, IRSDRYH) - PRH_TEND(JL, IRGDRYH))
IF (PARAMI%LNULLWETH) THEN
LLWETH(JL) = LLWETH(JL) .AND. ZRDRYH_INIT(JL) > 0.
ELSE
LLWETH(JL) = LLWETH(JL) .AND. ZRWETH_INIT(JL) > 0.
END IF
IF (.NOT. PARAMI%LWETHPOST) THEN
LLWETH(JL) = LLWETH(JL) .AND. PT(JL) < CST%XTT
END IF
LLDRYH(JL) = PT(JL) < CST%XTT .AND. ZRDRYH_INIT(JL) > 1.E-20 .AND.  MAX(0., ZRWETH_INIT(JL) - PRH_TEND(JL, IRIWETH) - PRH_TEND(JL, IRSWETH)) >  MAX(0., ZRDRYH_INIT(JL) - PRH_TEND(JL, IRIDRYH) - PRH_TEND(JL, IRSDRYH))
ELSE
PRH_TEND(JL, IFREEZ1) = 0.
PRH_TEND(JL, IFREEZ2) = 0.
ZRWETH_INIT(JL) = 0.
LLWETH(JL) = .FALSE.
LLDRYH(JL) = .FALSE.
END IF
END DO
IF (PARAMI%LCONVHG) THEN
!$mnh_expand_where(JL=1:KSIZE)
WHERE (LLDRYH(1:KSIZE))
ZRDRYHG(1:KSIZE) = ZRDRYH_INIT(1:KSIZE) * ZRWETH_INIT(1:KSIZE) / (ZRDRYH_INIT(1:KSIZE) + ZRWETH_INIT(1:KSIZE))
ELSEWHERE
ZRDRYHG(1:KSIZE) = 0.
END WHERE
!$mnh_end_expand_where(JL=1:KSIZE)
ELSE
ZRDRYHG(:) = 0.
END IF
DO JL=1, KSIZE
IF (LLWETH(JL)) THEN
PRCWETH(JL) = PRH_TEND(JL, IRCWETH)
PRIWETH(JL) = PRH_TEND(JL, IRIWETH)
PRSWETH(JL) = PRH_TEND(JL, IRSWETH)
PRGWETH(JL) = PRH_TEND(JL, IRGWETH)
PRRWETH(JL) = (ZRWETH_INIT(JL) - PRH_TEND(JL, IRIWETH) -  PRH_TEND(JL, IRSWETH) - PRH_TEND(JL, IRGWETH) -  PRH_TEND(JL, IRCWETH))
ELSE
PRCWETH(JL) = 0.
PRIWETH(JL) = 0.
PRSWETH(JL) = 0.
PRGWETH(JL) = 0.
PRRWETH(JL) = 0.
END IF
IF (LLDRYH(JL)) THEN
PRCDRYH(JL) = PRH_TEND(JL, IRCWETH)
PRIDRYH(JL) = PRH_TEND(JL, IRIDRYH)
PRSDRYH(JL) = PRH_TEND(JL, IRSDRYH)
PRRDRYH(JL) = PRH_TEND(JL, IRRWETH)
PRGDRYH(JL) = PRH_TEND(JL, IRGDRYH)
PRDRYHG(JL) = ZRDRYHG(JL)
ELSE
PRCDRYH(JL) = 0.
PRIDRYH(JL) = 0.
PRSDRYH(JL) = 0.
PRRDRYH(JL) = 0.
PRGDRYH(JL) = 0.
PRDRYHG(JL) = 0.
END IF
END DO
DO JL=1, KSIZE
IF (PRHT(JL) > ICED%XRTMIN(7) .AND. PT(JL) > CST%XTT .AND. LDCOMPUTE(JL)) THEN
IF (.NOT. LDSOFT) THEN
PRHMLTR(JL) = PRVT(JL) * PPRES(JL) / (CST%XEPSILO + PRVT(JL))
IF (PARAMI%LEVLIMIT) THEN
PRHMLTR(JL) = MIN(PRHMLTR(JL), EXP(CST%XALPW - CST%XBETAW / PT(JL) - CST%XGAMW * ALOG(PT(JL))))
END IF
PRHMLTR(JL) = PKA(JL) * (CST%XTT - PT(JL)) +  PDV(JL) * (CST%XLVTT + (CST%XCPV - CST%XCL) * (PT(JL) - CST%XTT))  * (CST%XESTT - PRHMLTR(JL)) / (CST%XRV * PT(JL))
PRHMLTR(JL) = MAX(0., (- PRHMLTR(JL) * (ICEP%X0DEPH * PLBDAH(JL) ** ICEP%XEX0DEPH +  ICEP%X1DEPH * PCJ(JL) * PLBDAH(JL) ** ICEP%XEX1DEPH) -  (PRH_TEND(JL, IRCWETH) + PRH_TEND(JL, IRRWETH)) *  (PRHODREF(JL) * CST%XCL * (CST%XTT - PT(JL)))) /  (PRHODREF(JL) * CST%XLMTT))
END IF
ELSE
PRHMLTR(JL) = 0.
END IF
END DO
IF (LHOOK) CALL DR_HOOK('ICE4_FAST_RH', 1, ZHOOK_HANDLE)
CONTAINS
INCLUDE "INTERP_MICRO.FUNC.H"
END SUBROUTINE ICE4_FAST_RH
END MODULE MODE_ICE4_FAST_RH1
