!#PYFT transfo: --removeVariable sub:ADD PBUF --simplify

MODULE MODD_BUF1
  TYPE BUF_t
    REAL :: XX
  END TYPE BUF_t
END MODULE MODD_BUF1

SUBROUTINE ADD(Z1, Z2, PBUF)
USE MODD_BUF, ONLY:BUF_t
IMPLICIT NONE
TYPE(BUF_t),INTENT(IN)::PBUF
REAL, INTENT(IN) :: Z1, Z2
END SUBROUTINE ADD
